### ISSUE TITLE
Not a issue, just a question, what does this module do

### ISSUE THREAD

**Issue by alain01** [XoopsModules25x/wgsimpleacc#4]
Hello,
what does this module do ?

Could you explain functionnalities in it ?

**Comment by ggoffy** [comment]
it is for a simple incomes/expenses calculation

**Comment by ggoffy** [comment]
module contains test data :)

**Comment by alain01** [comment]
First import, get an error
time exceed 30 s
then i retried and ok now !

**Comment by alain01** [comment]
Hey,
"Templates Outputs" what a good idea !!!

**Comment by ggoffy** [comment]
yes, you need different templates for e.g. a donation receipt, or of you lend equipment and so on

**Comment by alain01** [comment]
Like your "Import Sample Data",
like your "Feedback" tab,
I found your new idea, "Templates outputs" tab very very innovative => Create templates on the fly
Thank you for your imagination ! 
Big talent, big skills ! 

Hope all modules (not just yours) will use theses new functionnalities !
